/**
 * ============================================================
 * Global Career AI
 * Knowledge Intelligence State V1.1
 * ============================================================
 *
 * Domain contract representing knowledge intelligence
 * generated by the Knowledge Domain Intelligence Engine.
 *
 * No business logic belongs here.
 * ============================================================
 */

export interface KnowledgeState {
  dominantDomainId: string | null;

  averageScore: number;

  averageConfidence: number;

  domains: KnowledgeStateDomain[];
}

export interface KnowledgeStateDomain {
  domain: {
    id: string;
    name: string;
  };

  score: number;

  confidence: number;
}