/**
 * ============================================================
 * Global Career AI
 * Matching State Contract V1.2.1
 * ============================================================
 *
 * Domain contract representing Matching intelligence state.
 *
 * This contract belongs to the Intelligence Core.
 * It does not belong to Dashboard.
 *
 * No business logic.
 * No persistence.
 * ============================================================
 */

export interface MatchingOpportunity {

  /**
   * Real job/application identifier.
   */
  id: string;


  /**
   * Real job title originating from the Matching Engine.
   */
  title: string;


  /**
   * Match score produced by the Matching Engine.
   */
  score: number;


  /**
   * Real job country, when available.
   */
  country?: string;


  /**
   * Verified reasons generated by the Matching Engine.
   */
  reasons: string[];


  /**
   * Candidate skills that matched the opportunity.
   */
  matchedSkills: string[];


  /**
   * Candidate industries that matched the opportunity.
   */
  matchedIndustries: string[];

}


export interface MatchingState {

  /**
   * Overall Matching score.
   *
   * Represents the quality of the strongest real
   * opportunities evaluated by the Matching Engine.
   */
  score: number;


  /**
   * Confidence in the Matching intelligence.
   */
  confidence: number;


  /**
   * Verified candidate strengths detected against
   * real job opportunities.
   */
  strengths: string[];


  /**
   * Verified weaknesses / gaps.
   *
   * Empty when the Matching Engine does not have
   * sufficient candidate-side evidence to establish them.
   */
  weaknesses: string[];


  /**
   * Evidence generated by the Matching Engine.
   */
  evidence: string[];


  /**
   * Matching recommendations generated from
   * real matching signals.
   */
  recommendations: string[];


  /**
   * Real target roles extracted from the strongest
   * matching opportunities.
   */
  targetRoles: string[];


  /**
   * Real opportunities used to explain the strongest matches.
   *
   * These values originate from Matching Engine results.
   * No generated or inferred opportunities.
   */
  opportunities: MatchingOpportunity[];

}